### ISSUE TITLE
This WPF example doesn't work , can not drag any file. is it a bug or env problem?

### ISSUE THREAD

**Issue by AGIBuild** [dotnet/docs-desktop#1079]
**Test env:**
windows 10 21H1(19043.985)
VS 2019(16.9.6)
Project: WPF empty project (.net core 5.0)

**Result:**
Can not drag a file to the WPF program window.

**Root cause:**
Running Visual Studio as Administrator

Why drag\drop doesn't work as Administrator mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2210c27-5614-397a-9324-0f4f3d0de78b
* Version Independent ID: 2c129504-1e4f-9337-9aef-e571b034149e
* Content: [How to: Open a File That is Dropped on a RichTextBox Control - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/how-to-open-a-file-that-is-dropped-on-a-richtextbox-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/how-to-open-a-file-that-is-dropped-on-a-richtextbox-control.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/how-to-open-a-file-that-is-dropped-on-a-richtextbox-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@AGIBuild Hello. This is because when you run to debug your program in Visual Studio, the program is also being run as Administrator. Windows is blocking drag-and-drop operations between non-admin programs (the file explorer) and admin programs (your app).

I'm going to close this issue as it's something Windows is handling, not WPF or Visual Studio. Sorry ☹️
