### ISSUE TITLE
We should write document for Windows Forms .NET 6 right now, not .NET 5?

### ISSUE THREAD

**Issue by donhuvy** [dotnet/docs-desktop#1103]
I learned this from ASP.NET Core docs. The ultimate of reference document is supporting developers. Current version of .NET is .NET 5, but it still in progress, why we don't write document for Windows Forms .NET 6 right now? Even with Visual Studio 2022 or Visual Studio 2019 preview with many support design-time for Windows Forms.

- When .NET 6 release, the document of Windows Forms .NET 5 maybe finish.
- If applying the above proposal strategy, When .NET 6 release, the document of Windows Forms .NET 6 also finish. It will be better.

**Comment by adegeo** [comment]
@donhuvy thank you for the suggestion. The drop down shown on the site that displays .NET 5 and .NET Framework is really .NET vs. .NET Framework. Framework content will remain as is. When .NET 6 comes out, the existing .NET 5 content will be upgraded to call out .NET 6 instead of .NET 5. The same for Visual Studio 2020. The only time .NET 5 or VS 2019 will be called out is if there is something specific to them.
