### ISSUE TITLE
ToggleButton or DropDown button?

### ISSUE THREAD

**Issue by Benjy1979** [dotnet/docs-desktop#1262]
I've entered the "togglebutton" template and all I've gotten is a dropdown buttons. They are not toggle buttons.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9fb2c4c-1290-5db1-e2ae-0127667c6ef1
* Version Independent ID: 6964b4f5-f939-489f-636e-5c5f30ff1f0b
* Content: [ToggleButton Styles and Templates - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/togglebutton-styles-and-templates?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/togglebutton-styles-and-templates.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/togglebutton-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@Benjy1979 Hi there. I just checked this and they are indeed toggle buttons styled in the style of a combobox. The color changes are hard to notice but it does indeed toggle:

![image](https://user-images.githubusercontent.com/67293991/148106646-52334c3e-dd54-4809-bf8d-9d81aec996c9.png)

It's probably not the best example of a toggle button since it's not the common thing people would use it for. The documentation for .NET 4 isn't something we're currently improving unless its complete broken/dead. If this content gets moved for .NET 6 in the future, we'll be redoing all these templates.

I'll close this issue because I think it answers your question. Please feel free to respond with more information if it doesn't answer your question. Cheers!
