### ISSUE TITLE
Hard to understand MSDN document.

### ISSUE THREAD

**Issue by Jylee36** [dotnet/docs-desktop#1321]
[Enter feedback here]
Whenever I refer something on MSDN document, many examples are not helpful for newbies.
You don't provide whole set of example.
Please improve MSDN document information to provide whole set of examples not piece by piece.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0ad1362-3064-9816-47e7-7c29cd990173
* Version Independent ID: 08bd499b-178c-fb04-8980-41db01163b66
* Content: [How to: Implement Property Change Notification - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/data/how-to-implement-property-change-notification?view=netframeworkdesktop-4.8&source=docs)
* Content Source: [dotnet-desktop-guide/framework/wpf/data/how-to-implement-property-change-notification.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/data/how-to-implement-property-change-notification.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@Jylee36 Hello. Thank you for your feedback. Do you have a specific example of what isn't friendly? In general, a new user would want to first read [DataBinding Overview](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/data/data-binding-overview?view=netframeworkdesktop-4.8) first, so that they understand how the HOW TO articles end up working.
