### ISSUE TITLE
EmbeddedResource Update or Include

### ISSUE THREAD

**Issue by kennethhovsnow** [dotnet/docs-desktop#150]
[Enter feedback here]
Hi!
I'm in the process of migrating from .NET framework 4.8 to .NET 5 in a Winform solution. I have followed the document/page of how to migrate, and after some adjustments I finally managed to get the everything up and running. The bad feeling of that something is not correct, comes from this description:
"Notice that the Include was changed to Update on both the <Compile> and <EmbeddedResource> elements, and <SubType> was removed from <EmbeddedResource>"

I experienced that I had to switch back to Include in some cases: 

```xml
<EmbeddedResource Include="Dictionary\en_US.dic" />
```

and

```xml
<Compile Include="..\Shared\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
</Compile>
```

And then I wonder if have I changed from Include to Update in to many entries.
Should these have Update or Include?

```xml
<Compile Update="Api\TypeSystem.cs" />
<Compile Update="Bitmaps\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
</Compile>

<EmbeddedResource Update="IconGenerator\IconResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>IconResources.Designer.cs</LastGenOutput>
</EmbeddedResource>
<EmbeddedResource Update="Bitmaps\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
</EmbeddedResource>
```

Should <None> have subtypes?

```xml
<None Include="app.config">
      <SubType>Designer</SubType>
</None>
```

Another thing worth mentioning is that if you use Fody Weavers, you have to remove the `<Costura/>` entry in the FodyWeavers.xml, or you will get: 
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[20416] disadmin.exe' has exited with code -2147450740 (0x8000808c).

EDIT by adegeo to add code blocks for readability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98778ad1-6c20-6310-e4bc-9d9851a2270a
* Version Independent ID: d1ef1f43-00e2-b46f-4f38-6274a34f07f6
* Content: [Migrate a Windows Forms app to .NET 5 - Windows Forms .NET](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/migration/?view=netdesktop-5.0#feedback)
* Content Source: [dotnet-desktop-guide/net/winforms/migration/index.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/net/winforms/migration/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@kennethhovsnow Hello!

The change to `update` on the attribute was noted because I saw that in a fresh project. If you create a .NET 5 WPF project I noticed they used `update` instead of `include`. Looking at your case I think the template used `update` because the file types are automatically included in the project and these entries are instead to "update" the entry settings.

The new project system automatically includes references to files it knows about. So for example you don't need to specify a compile entry for `Api\TypeSystem.cs` as any csharp code file is automatically imported into the project as long as it lives in the root or below. Your entry for `..\Shared\SharedAssemblyInfo.cs` would still need to be `include` as it's in the `parent-folder/Shared` path and therefore not automatically included in the project.

I'm guessing that this is the same case for `.resx` files, the project system automatically knows about them so you just need to specify `update` instead of `include`. However your `.dic` file isn't known by the project system which is why you need to use `include`.

Regarding `subtype` I'm not sure. The designer system may understand that the `app.config` file uses a designer or not, so if it doesn't you would want to specify that `subtype`

I'll clarify these points in the article.

Maybe it's OK to just have them all as `Include`?

**Comment by adegeo** [comment]
@KlausLoeffelmann can you comment on this?

**Comment by kennethhovsnow** [comment]
Thank you for your answer, and sorry for late comment. The Bitmaps\Resources.Designer.cs only needed this: <Compile Update="Bitmaps\Resources.Designer.cs" /> after trying to delete the other stuff. 
Regarding subtypes, the app.config did not need subtype, only <None Include="app.config" />
