### ISSUE TITLE
Suspect that Microsoft Naming Conventions\Choices Causing Confusion

### ISSUE THREAD

**Issue by toddalbers** [dotnet/docs-desktop#1553]
I don't have a clear view of the different "project types" available in Visual Studio.  So, my suggestion might not be plausible.  But, I want to just offer it here since I don't think I am the only person having a difficult time keeping track of all of this.

I understand that things change as tech evolves.  And naming conventions may not be easy to make things easier to delineate one platform concept from another. But the naming of some of the Visual Studio project choices seem to possibly be contributing to confusion and misunderstanding.  It it difficult to differentiate between the items listed below.  And this is a small subset of the various general terms and also project types in Visual studio.  I know some of these listed below overlap or are redundant.  But, I think that highlights the problem even more.  It seems to me that renaming some of these terms\concepts\technologies\platforms in a way that helps differentiate the new from the old, and what one is versus the other is, etc. might help developers\users to differentiate between them a lot quicker.

- .NET
- .NET framework
- .NET core
- WPF
- Windows Forms App
- Windows Forms App (.NET Framework)
- WPF Application
- WPF Browser App (.NET framework)
- etc.

NOTE: I am not asking for an explanation of each of these.  I am simply trying to demonstrate how muddled the naming conventions appear to be.  I don't know if they can be renamed in way that helps with this problem or not.  But, maybe renaming or providing a description of the difference between one vs the other when you select two project types and hit a "Compare" button in Visual Studio might help.  Another idea might be to add a category of "Generation" to the project types where the oldest (and outdated) particular type of project would be 1 and the most recent "Generation" would be the generation with the highest number.

Using this type of "Generation" differentiator, I think the following would be correct:

PROJECT TYPE                                                      GENERATION
Windows Forms App                                                     1
Windows Forms App (.NET Framework)                        2
WPF Application. *                                                         3
WPF Browser App (.NET framework)                              ?   3?

If my understanding is correct, it seems to me it would have made more sense to name the 3rd generation project type above "Windows Forms App (Core or .NET Core)" instead.

This is just a general suggestion.  I think it would be a good move to make **very first step** of creating a project in Visual Studio as clear and easy as possible.  I could understand a new developer who wants to check out Visual Studio seeing all these choices right off the bat and deciding to go back to PyCharm or another IDE.  I think it would be helpful if the very first step in Visual Studio was more welcoming and less confusing and intimidating especially for someone trying to check out Visual Studio etc.  Just a suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 083cc028-0f4d-5261-6df3-f311703dbeae
* Version Independent ID: ea31e7d0-6f43-a3cf-7d56-0fb00373fce5
* Content: [Differences between .NET Framework and .NET - WPF .NET](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/migration/differences-from-net-framework?view=netdesktop-6.0)
* Content Source: [dotnet-desktop-guide/net/wpf/migration/differences-from-net-framework.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/migration/differences-from-net-framework.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@toddalbers I feel your pain related to this. There is quite a long story related to .NET/.NET Core/.NET Framework. This suggestion, though, you should file through Visual Studio's built-in feedback system. This way it gets to that team directly. In Visual Studio, press **Help** > **Send Feedback** > **Suggest a Feature**

As time move on, this confusion will lessen simply because things will fall out of support and off the menu list. For example, .NET Core 3.1 was the last version of .NET to use the "Core" name and is no longer in support as of December. So we'll be updating these articles and others like it to get rid of that and there'll simply be .NET 6/7/8/etc and .NET Framework.

At one point they did use the project wizard to let you select framework vs non-framework. So you just had selected new WPF App and a prompt would ask you to choose a framework. I think it was removed due to feedback from users that they didn't like it and preferred having two separate templates, one for .NET and the other for .NET Framework. So I don't think that will go away anytime soon, and .NET Framework will be supported for quite a long time.

As there isn't something really specific to do in this article, I'm going to close this issue.
