### ISSUE TITLE
Errors and inconsistencies

### ISSUE THREAD

**Issue by UTFDev** [dotnet/docs-desktop#1663]
There are errors/inconsistencies on this page as follows:

Bullet point 7: _Create an event handler for the Click event of the &New ToolStripMenuItem._

There is no &New menu item! The page only describes creating &File and &Window top level items and an &Open submenu item.

Bullet point 9: _Place code like the following in the &New ToolStripMenuItem to register the event handler._

?? How do you enter code into a menu item? Clarity is required here as to where the code should be located.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6f059cf-5b48-9964-7878-987b0e7af457
* Version Independent ID: 44d5fc14-e7fc-cd31-451c-b53aa4dd1e87
* Content: [How to: Create an MDI Window List with MenuStrip - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-create-an-mdi-window-list-with-menustrip-windows-forms?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-create-an-mdi-window-list-with-menustrip-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-create-an-mdi-window-list-with-menustrip-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I appreciate that you took the time to report this. Unfortunately we have a ton of this documentation for .NET Framework that is written like this. It's not comprehensive and assumes you know what you're doing. The other big problem is that a lot of the articles demonstrate entire examples through code only and not through Visual Studio.

I'm not really making sweeping changes on these articles because time is better spent rewriting these for the .NET docs area, as slow as that has been. Menu items and MDI hasn't been rewritten yet, sorry.

I'll at least add the `&new` to the steps.

For your question about the event, I believe you just have to open the designer, and first select the menu item then the submenu item. I think you can probably double click the submenu and it will automatically insert the Click event handler for you. Otherwise, you need to then use the **Properties** window to filter the events and then double click the Click event handler item to generate the handler. There is an example of how to do that [here](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-add-an-event-handler?view=netdesktop-7.0#handle-an-event---designer).
