### ISSUE TITLE
Changing settings for a project at design-time may erase settings set during run-time

### ISSUE THREAD

**Issue by BrianCook** [dotnet/docs-desktop#179]
This says nothing about the very inconvenient behavior which is that if you add a new setting, any saved values of your previous settings are all lost! You have to re-enter ALL the settings anytime you add a new one. Not friendly behavior, and not documented, nor documented what the workaround is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d9fd0d-871f-557d-972b-398bbe91f68a
* Version Independent ID: 4ca53b82-cb2b-1ccd-8fa8-e37557ce77ee
* Content: [How To: Create a New Setting at Design Time - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-create-a-new-setting-at-design-time?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-create-a-new-setting-at-design-time.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/advanced/how-to-create-a-new-setting-at-design-time.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 117824](https://dev.azure.com/msft-skilling/Content/_workitems/edit/117824)

**Comment by adegeo** [comment]
After doing some research I think we can update these how-to articles with a note about **User** settings. The overview for this doc area should probably mention something too. I think that the overview is out of date because it talks about the config file being saved as `user.config` where `user` is the user's name.

I believe the following statements are true:

1. The app uses a unique folder for **user** settings in the appdata directory. The folder is generated based on (1) the app's assembly information (2) the path to the executable. And, this folder (and the subsequent config file) is only generated when the app needs to store _changed_ **user** settings.

2. If any information about the assembly changes, or the assembly or has a different path (more than one copy of the executable, or simply moving the executable to a different folder) you'll get a new **user** settings folder path and your previously saved settings will not persist.

I'm still trying to understand the nuances
