### ISSUE TITLE
The control does not exist in tools. First, please explain how to add it. Thanks.

### ISSUE THREAD

**Issue by JavierAparicioGP** [dotnet/docs-desktop#1826]
### Type of issue

Typo

### Description

The control does not exist in tools. First, please explain how to add it. Thanks.

### Page URL

https://learn.microsoft.com/es-es/dotnet/desktop/winforms/controls/how-to-add-web-browser-capabilities-to-a-windows-forms-application?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-add-web-browser-capabilities-to-a-windows-forms-application.md

### Document Version Independent Id

be89c649-d099-fc47-6711-fcfaf3948b27

### Article author

@adegeo

**Comment by adegeo** [comment]
If the control is missing then you're using .NET 6-8 and not .NET Framework. This article was written for .NET Framework and the web browser control is based on the deprecated Internet Explorer. Since .NET 6-8+ doesn't support Internet Explorer, add the https://www.nuget.org/packages/Microsoft.Web.WebView2 package to your project and use that browser control. This package is based on the Edge browser.
