### ISSUE TITLE
Adding images to WinForms .NET 4.x documentation

### ISSUE THREAD

**Issue by hugmouse** [dotnet/docs-desktop#1967]
I am learning WinForms and .NET 4.7.2. I noticed a lack of images in the documentation in example sections and such. I'm a bit lazy to check the docs and then compile an example code just to see what it actually looks like visually, so I'd like to provide these screenshots for every lazy folk like me. It also seems that I need to upload them to the path like `./media/graphcismm-drawinggroup-order.png` (or at least how it's referenced in the doc below), which I have no idea how to do.

For example, there are some images in [WPF Graphics Rendering Overview][1] that are absolutely necessary in there to get the context right. So maybe I can do this for all the WinForms .NET 4.x docs where code examples are present?

Oh, and I also want to wish you a Happy New Year! Who doesn't like to create some issues at the end of the year?

[1]: https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/graphics-multimedia/wpf-graphics-rendering-overview.md

**Comment by adegeo** [comment]
Greetings! I agree with you completely. These articles were written a long time ago and for whatever reason the original authors decided not to have images. Unfortunately we're not going back and updating the .NET Framework content. As content gets moved into the new .NET area, I do add images where appropriate.

For example, when I migrated all the concepts about control layout, I added a lot of images and even animated gifs: https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/layout?view=netdesktop-9.0 because it really makes sense to visualize these concepts as you read about them.

I'm going to close this issue since I won't be updating the old docs. Sorry about that!
