### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by LJ9999** [dotnet/docs-desktop#206]
This just doesn't work. Seems to me information is missing. I have a form. I implemented the sample, put a breakpoint on it, pressed a key. It's never called. 

Thanks for nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 959083dc-eeea-74f5-4071-fd8c23b166b2
* Version Independent ID: baa42008-a238-0f1f-621c-f18de5dc896c
* Content: [Handle keyboard input at the Form level - Windows Forms .NET](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/input-keyboard/how-to-handle-forms?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/winforms/input-keyboard/how-to-handle-forms.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/net/winforms/input-keyboard/how-to-handle-forms.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I think I wrote this with the thought that the reader would be familiar with how to handle a events, and specifically, an event from the UI. This code presented is the handler code but you still have to hook it up to the original `KeyPress` event.

I do value your feedback and I would love to understand how you arrived here without the appropriate knowledge:
1. Is this your first WinForms app?
2. What experience do you have in Visual Studio?
3. Did you complete the [create a new app](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/get-started/create-app-visual-studio?view=netdesktop-5.0) tutorial?

I've been thinking about documenting common Visual Studio tasks that a WinForms/WPF developer would do, and possibly, avoid the problem you find yourself in.

To answer your specific problem, you would open the form in the designer, click on the form so that it's the selected object, then se the **Properties** pane to find the `KeyPress` event. This is detailed in the [create a new app, handle events section](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/get-started/create-app-visual-studio?view=netdesktop-5.0#handle-events) but for a button. The same process applies.

This should solve your problem. Even though I'm going to close this issue, please feel free to respond.
