### ISSUE TITLE
What is the point of this page ?

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/docs-desktop#31]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5088aa3f-addb-a600-bc90-9c1e6a4c8dfd
* Version Independent ID: 053d6ccf-6dff-ebb9-6a18-3adc0ea9f5f8
* Content: [Windows Forms - .NET](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/winforms/index.md](https://github.com/dotnet/docs-desktop/blob/live/dotnet-desktop-guide/net/winforms/index.md)
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
It's a placeholder so that version selection works, until I get the Winforms content ported and versioned for .NET 5. The issue tracking this is at https://github.com/dotnet/docs/issues/10648 but I'll be moving that and all the other related issues here. Work on ported was on hold while we created and migrated the winforms documentation to this new repo.

**Comment by adegeo** [comment]
I'm going to close this issue. Cheers!
