### ISSUE TITLE
This page is mis-named

### ISSUE THREAD

**Issue by CedricCicada** [dotnet/docs-desktop#51]
This page does not answer the question of how to add an event at run time.  It illustrates adding one during design, but not during run-time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b01e2f08-f620-3402-46f5-65ffb4e1dba6
* Version Independent ID: 114243e3-25bd-dc0d-1364-e7d573205edc
* Content: [How to: Create Event Handlers at Run Time - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/how-to-create-event-handlers-at-run-time-for-windows-forms?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/how-to-create-event-handlers-at-run-time-for-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/live/dotnet-desktop-guide/framework/winforms/how-to-create-event-handlers-at-run-time-for-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@CedricCicada Hello. Design-time is when you're using the Visual Studio designer. Run-time is when the program is running. Since the coder adds the code `button1.Click += new EventHandler(button1_Click);` into the program, when the program is running and enounters that statement, it adds the handler at that moment, in run-time.
